### ISSUE TITLE
Webserver produced by Flask script fails with syntax error in `[...].chunk.js` file

### ISSUE THREAD

**Issue by rolyp** [tgve/eatlas-template#31]
Running the [Flask instructions](https://github.com/tgve/app/tree/release/Python) starts a webserver at http://127.0.0.1:5000 but going to that page fails:

![Screenshot 2022-02-15 at 12 54 11](https://user-images.githubusercontent.com/121074/154066097-0da3f946-ac12-405f-a9f3-046b65c3a169.png)

See the [Dockerfile](https://github.com/tgve/app/blob/release/Dockerfile.Python) for a reproducible example.

The obvious choices are to either:
1. support Python properly and fix the instructions/Dockerfile
1. drop Python support and drop the instructions/Dockerfile

- [x] fix problem in current Flask configuration (as captured in Dockerfile.Python)
- <s>validation script for `cross-origin.md` instructions</s>

**Comment by layik** [comment]
I will send the minimum instructions and I think we should leave it there for users to take it further. The original doc had enough but not as reproducible commands

**Comment by layik** [comment]
I suggest we delete the second checkbox and the CORS script.

**Comment by layik** [comment]
#33 is merged does that mean we can close this @rolyp? Reopen if not!

**Comment by rolyp** [comment]
@layik This doesn't quite fix it -- I should have explained the methodology. The idea is to have a `Dockerfile.Python` that serves as executable documentation (and similarly for R, NodeJS). Actually there is a higher-level script -- `serve.sh` in the Python folder -- that builds the Docker image and then starts a container serving the app. So a fix to this problem means a fix to the Dockerfile such that if I run `serve.sh`,  I have a running instance of the application.

(Working on a similar setup for R as #36, and we can do the same for NodeJS as well. Automation is the best kind of documentation! Adjusted title of this issue to make the problem clearer.)

**Comment by layik** [comment]
@rolyp I see no reason for two Dockerfiles.

**Comment by rolyp** [comment]
@layik `Dockerfile.Python` documents the workflow and configuration required to serve the app via Flask. The advantage of scripting the steps (rather than just writing them down  in a `README`) is that the documentation is “reproducible” – the reader can execute it to get a running application. Text in a `README` can easily miss important steps and goes stale quickly.

**Comment by layik** [comment]
We agreed not to go there we deleted the checkbox (edit: sorry that was for the cors). If someone needs an image the R based one can well do their job.

**Comment by layik** [comment]
Let's delete NodeJS one before I take more precious time from you Roly.
