### ISSUE TITLE
Executable docs for R app hosting

### ISSUE THREAD

**Issue by rolyp** [tgve/eatlas-template#36]
The instructions for hosting in R (via Plumber) should follow the same pattern as the Python instructions, i.e. be presented as reproducible scripts.
- [x] Move R instructions from `notes/serving-data.md` to `R/README.md`
- [x] rename `Dockerfile` to `Dockerfile.R`
- [x] where appropriate move documentation from `R/README.md` to `plumber.R`, `run.R` or `Dockerfile.R`
- [x] remove CORS documentation (by analogy with Python)?
- [x] <s>factor `Dockerfile.R` through `run.R`?</s> delete `run.R` -- subsumed by instructions in `Docker.R`
- #44
- [x] simplify deploy step of GitHub Pages action
- [x] `docker.yml` workflow to validate Docker scripts

**Comment by layik** [comment]
Happy to help @rolyp!

**Comment by layik** [comment]
I suggest we suffice with #39 and close this ticket.
